# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

sudo: false

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='pytest KCWIPyDRP'
        - PYTHON_VERSION=3.6

    matrix:
        - SETUP_CMD='egg_info' TEST_CMD='python --version'

matrix:
    include:
        # pytest pip fallback, conda package for 3.1 is not available for py3.4
        - os: linux
          env: PYTHON_VERSION=3.4 PYTEST_VERSION=3.1

        - os: linux
          env: MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'

    allow_failures:
        - os: linux
          env: PYTHON_VERSION=3.4 PYTEST_VERSION=3.1 PIP_FALLBACK=false

script:
   - eval $TEST_CMD

